version: "3.9"
services:
  jupyter:
    container_name: orbit-elm-jupyter
    image: jupyter/datascience-notebook:latest
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./data:/home/jovyan/work
    command: start-notebook.sh